version: 1
accounts:
  - name: cold
    coins: ["100000000000000usge"]
    mnemonic: stairs lobster urge panic air mad acoustic find coin used valid unaware people clog excuse velvet couple draw say slow polar glass pepper scrap
  - name: hot
    mnemonic: assist theme marine fan crucial ancient leopard when away stand utility tooth silent regret vibrant unknown demand device tiny useless adapt manage tiny provide
  - name: admin
    mnemonic: patch donor arena plug burst silk cram day charge valve prize awake remind wolf resource silk oyster man tray police ritual immune foot beef
  - name: oracle
    mnemonic: better ketchup radio relax scheme worth foam utility bamboo moon slab trade tackle hobby once pass daughter isolate nice cost level swim view final
validators:
  - name: cold
    bonded: "1000000000000usge"
    app:
      minimum-gas-prices: "10usge"
genesis:
  app_state:
    bank:
      balances:
        - address: "sge12m8k4n37tcqt5fk0s90jk3t8gz8rkgl33cu407"
          coins: [{ "denom": "usge", "amount": "10000000000" }]
      supply:
        - denom: "usge"
          amount: "10000000000"
    staking:
      params:
        bond_denom: "usge"
    crisis:
      constant_fee:
        denom: "usge"
        amount: "1000"
    ovm:
      key_vault:
        public_keys:
          [
            "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAdUWfzVUf4BqsHvErsJoXIaIpO60CHXfaaef+xKU3bbY=\n-----END PUBLIC KEY-----",
            "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEA58w+676YVp61kjXDrteK8hDxulq5zbF6sNHQt3Lt5Ng=\n-----END PUBLIC KEY-----",
            "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAw5iPKVbSvyF1A1HDFaWMGlhBp/xTU70i8lMgOml79WM=\n-----END PUBLIC KEY-----",
            "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAueEgZMdKn6Bp0mcG04HrNAt1a0o7+0eNliQCNmbxkOQ=\n-----END PUBLIC KEY-----",
            "-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAkMnWRwXXVlQqhpHq7LNVGwqA/E2LQY/6remOtilPKpI=\n-----END PUBLIC KEY-----",
          ]
    gov:
      params:
        expedited_min_deposit: [{ amount: "2", denom: "usge" }]
        min_deposit: [{ amount: "1", denom: "usge" }]
        voting_period: "40s"
        expedited_voting_period: "30s"
    bet:
      params:
        constraints:
          min_amount: "1000000"
          fee: "100"
    mint:
      minter:
        phase_provisions: "100000000000000.000000000000000000"
        inflation: "0.1"
        phase_step: "1"
        truncated_tokens: "0"
      params:
        mint_denom: "usge"
        blocks_per_year: "100"
        phases: [{ inflation: "0.100000000000000000", year_coefficient: "1" }]
        exclude_amount: "500000000000"
    orderbook:
      params:
        requeue_threshold: "1000"
