// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sge/legacy/bet/v1beta/params.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	// batch_settlement_count is the batch settlement bet count.
	BatchSettlementCount uint32 `protobuf:"varint,1,opt,name=batch_settlement_count,json=batchSettlementCount,proto3" json:"batch_settlement_count,omitempty"`
	// max_bet_by_uid_query_count is the maximum bet by uid query items count.
	MaxBetByUidQueryCount uint32 `protobuf:"varint,2,opt,name=max_bet_by_uid_query_count,json=maxBetByUidQueryCount,proto3" json:"max_bet_by_uid_query_count,omitempty"`
	// constraints is the bet constraints.
	Constraints Constraints `protobuf:"bytes,3,opt,name=constraints,proto3" json:"constraints" yaml:"constraints"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_a4817f7b4190cb0c, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetBatchSettlementCount() uint32 {
	if m != nil {
		return m.BatchSettlementCount
	}
	return 0
}

func (m *Params) GetMaxBetByUidQueryCount() uint32 {
	if m != nil {
		return m.MaxBetByUidQueryCount
	}
	return 0
}

func (m *Params) GetConstraints() Constraints {
	if m != nil {
		return m.Constraints
	}
	return Constraints{}
}

func init() {
	proto.RegisterType((*Params)(nil), "sge.legacy.bet.Params")
}

func init() {
	proto.RegisterFile("sge/legacy/bet/v1beta/params.proto", fileDescriptor_a4817f7b4190cb0c)
}

var fileDescriptor_a4817f7b4190cb0c = []byte{
	// 313 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xbf, 0x4e, 0xf3, 0x30,
	0x14, 0xc5, 0xe3, 0xef, 0x43, 0x1d, 0x52, 0xc1, 0x10, 0x15, 0x54, 0x05, 0x29, 0xad, 0xb2, 0xd0,
	0xa5, 0xb1, 0xf8, 0xb3, 0xd0, 0x31, 0x1d, 0x58, 0xa1, 0x88, 0x01, 0x96, 0xc8, 0x4e, 0xaf, 0xdc,
	0x88, 0x3a, 0x2e, 0xf1, 0x0d, 0xd4, 0x6f, 0xc1, 0xc8, 0xc8, 0xe3, 0x74, 0xec, 0x88, 0x18, 0x2a,
	0xd4, 0xbe, 0x01, 0x4f, 0x80, 0x92, 0x54, 0x10, 0x24, 0xb6, 0x2b, 0xfd, 0xce, 0xf9, 0xc9, 0x3e,
	0xb6, 0xaf, 0x05, 0xd0, 0x29, 0x08, 0x16, 0x1b, 0xca, 0x01, 0xe9, 0xe3, 0x31, 0x07, 0x64, 0x74,
	0xc6, 0x32, 0x26, 0x75, 0x30, 0xcb, 0x14, 0x2a, 0x67, 0x4f, 0x0b, 0x08, 0xaa, 0x4c, 0xc0, 0x01,
	0xdd, 0x96, 0x50, 0x42, 0x95, 0x88, 0x16, 0x57, 0x95, 0x72, 0x8f, 0xfe, 0x36, 0xc5, 0x2a, 0xd5,
	0x98, 0xb1, 0x24, 0xc5, 0xad, 0xce, 0x7f, 0x27, 0x76, 0xe3, 0xb2, 0xf4, 0x3b, 0x67, 0xf6, 0x01,
	0x67, 0x18, 0x4f, 0x22, 0x0d, 0x88, 0x53, 0x90, 0x90, 0x62, 0x14, 0xab, 0x3c, 0xc5, 0x36, 0xe9,
	0x92, 0xde, 0xee, 0xa8, 0x55, 0xd2, 0xeb, 0x6f, 0x38, 0x2c, 0x98, 0x73, 0x6e, 0xbb, 0x92, 0xcd,
	0x23, 0x0e, 0x18, 0x71, 0x13, 0xe5, 0xc9, 0x38, 0x7a, 0xc8, 0x21, 0x33, 0xdb, 0xe6, 0xbf, 0xb2,
	0xb9, 0x2f, 0xd9, 0x3c, 0x04, 0x0c, 0xcd, 0x4d, 0x32, 0xbe, 0x2a, 0x68, 0x55, 0xbd, 0xb5, 0x9b,
	0xb5, 0x07, 0xb5, 0xff, 0x77, 0x49, 0xaf, 0x79, 0x72, 0x18, 0xfc, 0xfe, 0x60, 0x30, 0xfc, 0x89,
	0x84, 0xee, 0x62, 0xd5, 0xb1, 0x3e, 0x57, 0x1d, 0xc7, 0x30, 0x39, 0x1d, 0xf8, 0xb5, 0xb6, 0x3f,
	0xaa, 0xbb, 0x06, 0x3b, 0x2f, 0xaf, 0x1d, 0x2b, 0xbc, 0x58, 0xac, 0x3d, 0xb2, 0x5c, 0x7b, 0xe4,
	0x63, 0xed, 0x91, 0xe7, 0x8d, 0x67, 0x2d, 0x37, 0x9e, 0xf5, 0xb6, 0xf1, 0xac, 0xbb, 0xbe, 0x48,
	0x70, 0x92, 0xf3, 0x20, 0x56, 0x92, 0x6a, 0x01, 0xfd, 0x14, 0xf0, 0x49, 0x65, 0xf7, 0xc5, 0x4d,
	0xe7, 0xf5, 0xe1, 0xd0, 0xcc, 0x40, 0xf3, 0x46, 0x39, 0xd6, 0xe9, 0x57, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x78, 0x7c, 0x12, 0x98, 0xa1, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Constraints.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.MaxBetByUidQueryCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.MaxBetByUidQueryCount))
		i--
		dAtA[i] = 0x10
	}
	if m.BatchSettlementCount != 0 {
		i = encodeVarintParams(dAtA, i, uint64(m.BatchSettlementCount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BatchSettlementCount != 0 {
		n += 1 + sovParams(uint64(m.BatchSettlementCount))
	}
	if m.MaxBetByUidQueryCount != 0 {
		n += 1 + sovParams(uint64(m.MaxBetByUidQueryCount))
	}
	l = m.Constraints.Size()
	n += 1 + l + sovParams(uint64(l))
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BatchSettlementCount", wireType)
			}
			m.BatchSettlementCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BatchSettlementCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxBetByUidQueryCount", wireType)
			}
			m.MaxBetByUidQueryCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.MaxBetByUidQueryCount |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constraints", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Constraints.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
