// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: sge/legacy/orderbook/v1beta/exposure.proto

package types

import (
	cosmossdk_io_math "cosmossdk.io/math"
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// OrderBookOddsExposure represents the exposures taken on odds.
type OrderBookOddsExposure struct {
	// order_book_uid is the universally unique identifier corresponding to the
	// order book.
	OrderBookUID string `protobuf:"bytes,1,opt,name=order_book_uid,proto3" json:"order_book_uid"`
	// odds_uid is the universally unique identifier of the odds.
	OddsUID string `protobuf:"bytes,2,opt,name=odds_uid,proto3" json:"odds_uid"`
	// fulfillment_queue is the slice of indices of participations to be
	// fulfilled.
	FulfillmentQueue []uint64 `protobuf:"varint,3,rep,packed,name=fulfillment_queue,json=fulfillmentQueue,proto3" json:"fulfillment_queue,omitempty" yaml:"fulfillment_queue"`
}

func (m *OrderBookOddsExposure) Reset()      { *m = OrderBookOddsExposure{} }
func (*OrderBookOddsExposure) ProtoMessage() {}
func (*OrderBookOddsExposure) Descriptor() ([]byte, []int) {
	return fileDescriptor_87d0a6eb50df3146, []int{0}
}
func (m *OrderBookOddsExposure) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OrderBookOddsExposure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OrderBookOddsExposure.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OrderBookOddsExposure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderBookOddsExposure.Merge(m, src)
}
func (m *OrderBookOddsExposure) XXX_Size() int {
	return m.Size()
}
func (m *OrderBookOddsExposure) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderBookOddsExposure.DiscardUnknown(m)
}

var xxx_messageInfo_OrderBookOddsExposure proto.InternalMessageInfo

// ParticipationExposure represents the exposures taken on odds by
// participations.
type ParticipationExposure struct {
	// order_book_uid is the universally unique identifier of the order book that
	// the exposure is being set.
	OrderBookUID string `protobuf:"bytes,1,opt,name=order_book_uid,proto3" json:"order_book_uid"`
	// odds_uid is the odds universal unique identifier that the exposure is being
	// set.
	OddsUID string `protobuf:"bytes,2,opt,name=odds_uid,proto3" json:"odds_uid"`
	// participation_index is the index of participation in the queue.
	ParticipationIndex uint64 `protobuf:"varint,3,opt,name=participation_index,json=participationIndex,proto3" json:"participation_index,omitempty" yaml:"participation_index"`
	// exposure is the total exposure taken on given odds.
	Exposure cosmossdk_io_math.Int `protobuf:"bytes,4,opt,name=exposure,proto3,customtype=cosmossdk.io/math.Int" json:"exposure" yaml:"exposure"`
	// bet_amount is the total bet amount corresponding to the exposure.
	BetAmount cosmossdk_io_math.Int `protobuf:"bytes,5,opt,name=bet_amount,json=betAmount,proto3,customtype=cosmossdk.io/math.Int" json:"bet_amount" yaml:"bet_amount"`
	// is_fulfilled represents if the participation exposure is fulfilled or not.
	IsFulfilled bool `protobuf:"varint,6,opt,name=is_fulfilled,json=isFulfilled,proto3" json:"is_fulfilled,omitempty" yaml:"is_fulfilled"`
	// round is the current round number in the queue.
	Round uint64 `protobuf:"varint,7,opt,name=round,proto3" json:"round,omitempty" yaml:"round"`
}

func (m *ParticipationExposure) Reset()      { *m = ParticipationExposure{} }
func (*ParticipationExposure) ProtoMessage() {}
func (*ParticipationExposure) Descriptor() ([]byte, []int) {
	return fileDescriptor_87d0a6eb50df3146, []int{1}
}
func (m *ParticipationExposure) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ParticipationExposure) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ParticipationExposure.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ParticipationExposure) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ParticipationExposure.Merge(m, src)
}
func (m *ParticipationExposure) XXX_Size() int {
	return m.Size()
}
func (m *ParticipationExposure) XXX_DiscardUnknown() {
	xxx_messageInfo_ParticipationExposure.DiscardUnknown(m)
}

var xxx_messageInfo_ParticipationExposure proto.InternalMessageInfo

func init() {
	proto.RegisterType((*OrderBookOddsExposure)(nil), "sge.legacy.orderbook.OrderBookOddsExposure")
	proto.RegisterType((*ParticipationExposure)(nil), "sge.legacy.orderbook.ParticipationExposure")
}

func init() {
	proto.RegisterFile("sge/legacy/orderbook/v1beta/exposure.proto", fileDescriptor_87d0a6eb50df3146)
}

var fileDescriptor_87d0a6eb50df3146 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x93, 0x31, 0x6f, 0xd3, 0x4e,
	0x18, 0xc6, 0xed, 0x7f, 0xd2, 0x36, 0xbd, 0x7f, 0x04, 0xad, 0xdb, 0xa8, 0x56, 0x85, 0x7c, 0xd1,
	0x0d, 0x28, 0x42, 0xc2, 0x06, 0xb2, 0x65, 0xc3, 0x02, 0xa4, 0x20, 0x50, 0xa8, 0x25, 0x16, 0x16,
	0xcb, 0xce, 0x5d, 0xdd, 0x53, 0x62, 0x5f, 0xf0, 0x9d, 0x21, 0xf9, 0x06, 0x8c, 0x8c, 0x8c, 0xf9,
	0x38, 0x1d, 0x3b, 0x22, 0x86, 0x13, 0x72, 0x16, 0xc4, 0x86, 0x67, 0x06, 0xe4, 0x73, 0x63, 0xd2,
	0x16, 0x89, 0x95, 0xed, 0xbd, 0xe7, 0x7d, 0x9e, 0xdf, 0xdd, 0xf9, 0xfc, 0x82, 0x7b, 0x3c, 0x22,
	0xce, 0x94, 0x44, 0xc1, 0x78, 0xe1, 0xb0, 0x14, 0x93, 0x34, 0x64, 0x6c, 0xe2, 0xbc, 0x7b, 0x18,
	0x12, 0x11, 0x38, 0x64, 0x3e, 0x63, 0x3c, 0x4b, 0x89, 0x3d, 0x4b, 0x99, 0x60, 0xc6, 0x21, 0x8f,
	0x88, 0x5d, 0x79, 0xed, 0xda, 0x7b, 0x7c, 0x18, 0xb1, 0x88, 0x29, 0x83, 0x53, 0x56, 0x95, 0x17,
	0xfd, 0xd0, 0x41, 0x67, 0x54, 0x7a, 0x5c, 0xc6, 0x26, 0x23, 0x8c, 0xf9, 0xd3, 0x4b, 0x96, 0xf1,
	0x1c, 0xdc, 0x52, 0x61, 0xbf, 0x4c, 0xfb, 0x19, 0xc5, 0xa6, 0xde, 0xd5, 0x7b, 0xbb, 0x2e, 0xca,
	0x25, 0x6c, 0xd7, 0x91, 0xd7, 0xc3, 0x27, 0xdf, 0x25, 0xbc, 0xe6, 0xf4, 0xae, 0xad, 0x8d, 0x3e,
	0x68, 0x31, 0x8c, 0xb9, 0xa2, 0xfc, 0xa7, 0x28, 0x47, 0xb9, 0x84, 0x3b, 0xe5, 0x7e, 0x15, 0xa0,
	0x6e, 0x7b, 0x75, 0x65, 0x0c, 0xc1, 0xfe, 0x69, 0x36, 0x3d, 0xa5, 0xd3, 0x69, 0x4c, 0x12, 0xe1,
	0xbf, 0xcd, 0x48, 0x46, 0xcc, 0x46, 0xb7, 0xd1, 0x6b, 0xba, 0x77, 0x0a, 0x09, 0xcd, 0x45, 0x10,
	0x4f, 0x07, 0xe8, 0x86, 0x05, 0x79, 0x7b, 0x1b, 0xda, 0x49, 0x29, 0x0d, 0xda, 0x1f, 0x96, 0x50,
	0xfb, 0xb4, 0x84, 0xda, 0xb7, 0x25, 0xd4, 0xd0, 0xcf, 0x06, 0xe8, 0xbc, 0x0a, 0x52, 0x41, 0xc7,
	0x74, 0x16, 0x08, 0xca, 0x92, 0x7f, 0xe7, 0xce, 0x23, 0x70, 0x30, 0xdb, 0x3c, 0x99, 0x4f, 0x13,
	0x4c, 0xe6, 0x66, 0xa3, 0xab, 0xf7, 0x9a, 0xae, 0x55, 0x48, 0x78, 0x5c, 0xdd, 0xfa, 0x0f, 0x26,
	0xe4, 0x19, 0x57, 0xd4, 0x61, 0x29, 0x1a, 0x2f, 0x40, 0x6b, 0xfd, 0x77, 0x98, 0x4d, 0x75, 0x8a,
	0x07, 0xe7, 0x12, 0x6a, 0x5f, 0x24, 0xec, 0x8c, 0x19, 0x8f, 0x19, 0xe7, 0x78, 0x62, 0x53, 0xe6,
	0xc4, 0x81, 0x38, 0xb3, 0x87, 0x89, 0x28, 0x24, 0xbc, 0x5d, 0x6d, 0xb1, 0x8e, 0x21, 0xaf, 0x26,
	0x18, 0x27, 0x00, 0x84, 0x44, 0xf8, 0x41, 0xcc, 0xb2, 0x44, 0x98, 0x5b, 0x8a, 0xf7, 0xe8, 0x6f,
	0xbc, 0xfd, 0x8a, 0xf7, 0x3b, 0x88, 0xbc, 0xdd, 0x90, 0x88, 0xc7, 0xaa, 0x36, 0x06, 0xa0, 0x4d,
	0xb9, 0x7f, 0xf9, 0x62, 0x04, 0x9b, 0xdb, 0x5d, 0xbd, 0xd7, 0x72, 0x8f, 0x0a, 0x09, 0x0f, 0xaa,
	0xdc, 0x66, 0x17, 0x79, 0xff, 0x53, 0xfe, 0x6c, 0xbd, 0x32, 0xee, 0x82, 0xad, 0x94, 0x65, 0x09,
	0x36, 0x77, 0xd4, 0xf7, 0xd9, 0x2b, 0x24, 0x6c, 0x57, 0x21, 0x25, 0x23, 0xaf, 0x6a, 0x5f, 0x7d,
	0x7e, 0xf7, 0xe5, 0x79, 0x6e, 0xe9, 0x17, 0xb9, 0xa5, 0x7f, 0xcd, 0x2d, 0xfd, 0xe3, 0xca, 0xd2,
	0x2e, 0x56, 0x96, 0xf6, 0x79, 0x65, 0x69, 0x6f, 0xfa, 0x11, 0x15, 0x67, 0x59, 0x68, 0x8f, 0x59,
	0xec, 0xf0, 0x88, 0xdc, 0x4f, 0x88, 0x78, 0xcf, 0xd2, 0x49, 0x59, 0x3b, 0xf3, 0x9b, 0xd3, 0x27,
	0x16, 0x33, 0xc2, 0xc3, 0x6d, 0x35, 0x48, 0xfd, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3d, 0x52,
	0x13, 0x9b, 0xa2, 0x03, 0x00, 0x00,
}

func (m *OrderBookOddsExposure) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OrderBookOddsExposure) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OrderBookOddsExposure) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FulfillmentQueue) > 0 {
		dAtA2 := make([]byte, len(m.FulfillmentQueue)*10)
		var j1 int
		for _, num := range m.FulfillmentQueue {
			for num >= 1<<7 {
				dAtA2[j1] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j1++
			}
			dAtA2[j1] = uint8(num)
			j1++
		}
		i -= j1
		copy(dAtA[i:], dAtA2[:j1])
		i = encodeVarintExposure(dAtA, i, uint64(j1))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OddsUID) > 0 {
		i -= len(m.OddsUID)
		copy(dAtA[i:], m.OddsUID)
		i = encodeVarintExposure(dAtA, i, uint64(len(m.OddsUID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrderBookUID) > 0 {
		i -= len(m.OrderBookUID)
		copy(dAtA[i:], m.OrderBookUID)
		i = encodeVarintExposure(dAtA, i, uint64(len(m.OrderBookUID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ParticipationExposure) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ParticipationExposure) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ParticipationExposure) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Round != 0 {
		i = encodeVarintExposure(dAtA, i, uint64(m.Round))
		i--
		dAtA[i] = 0x38
	}
	if m.IsFulfilled {
		i--
		if m.IsFulfilled {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x30
	}
	{
		size := m.BetAmount.Size()
		i -= size
		if _, err := m.BetAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintExposure(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Exposure.Size()
		i -= size
		if _, err := m.Exposure.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintExposure(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	if m.ParticipationIndex != 0 {
		i = encodeVarintExposure(dAtA, i, uint64(m.ParticipationIndex))
		i--
		dAtA[i] = 0x18
	}
	if len(m.OddsUID) > 0 {
		i -= len(m.OddsUID)
		copy(dAtA[i:], m.OddsUID)
		i = encodeVarintExposure(dAtA, i, uint64(len(m.OddsUID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.OrderBookUID) > 0 {
		i -= len(m.OrderBookUID)
		copy(dAtA[i:], m.OrderBookUID)
		i = encodeVarintExposure(dAtA, i, uint64(len(m.OrderBookUID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintExposure(dAtA []byte, offset int, v uint64) int {
	offset -= sovExposure(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OrderBookOddsExposure) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderBookUID)
	if l > 0 {
		n += 1 + l + sovExposure(uint64(l))
	}
	l = len(m.OddsUID)
	if l > 0 {
		n += 1 + l + sovExposure(uint64(l))
	}
	if len(m.FulfillmentQueue) > 0 {
		l = 0
		for _, e := range m.FulfillmentQueue {
			l += sovExposure(uint64(e))
		}
		n += 1 + sovExposure(uint64(l)) + l
	}
	return n
}

func (m *ParticipationExposure) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.OrderBookUID)
	if l > 0 {
		n += 1 + l + sovExposure(uint64(l))
	}
	l = len(m.OddsUID)
	if l > 0 {
		n += 1 + l + sovExposure(uint64(l))
	}
	if m.ParticipationIndex != 0 {
		n += 1 + sovExposure(uint64(m.ParticipationIndex))
	}
	l = m.Exposure.Size()
	n += 1 + l + sovExposure(uint64(l))
	l = m.BetAmount.Size()
	n += 1 + l + sovExposure(uint64(l))
	if m.IsFulfilled {
		n += 2
	}
	if m.Round != 0 {
		n += 1 + sovExposure(uint64(m.Round))
	}
	return n
}

func sovExposure(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozExposure(x uint64) (n int) {
	return sovExposure(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OrderBookOddsExposure) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExposure
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OrderBookOddsExposure: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OrderBookOddsExposure: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderBookUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExposure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExposure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExposure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderBookUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OddsUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExposure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExposure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExposure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OddsUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowExposure
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.FulfillmentQueue = append(m.FulfillmentQueue, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowExposure
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthExposure
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthExposure
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.FulfillmentQueue) == 0 {
					m.FulfillmentQueue = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowExposure
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.FulfillmentQueue = append(m.FulfillmentQueue, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field FulfillmentQueue", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipExposure(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExposure
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ParticipationExposure) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowExposure
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ParticipationExposure: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ParticipationExposure: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderBookUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExposure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExposure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExposure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderBookUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OddsUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExposure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExposure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExposure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OddsUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ParticipationIndex", wireType)
			}
			m.ParticipationIndex = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExposure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ParticipationIndex |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exposure", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExposure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExposure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExposure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Exposure.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BetAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExposure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthExposure
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthExposure
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BetAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsFulfilled", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExposure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsFulfilled = bool(v != 0)
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Round", wireType)
			}
			m.Round = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowExposure
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Round |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipExposure(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthExposure
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipExposure(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowExposure
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExposure
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowExposure
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthExposure
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupExposure
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthExposure
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthExposure        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowExposure          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupExposure = fmt.Errorf("proto: unexpected end of group")
)
